default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] || 'dev' %>
  password: <%= ENV['DB_PASSWORD'] || '321321' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: sum_development

test:
  <<: *default
  database: sum_test

production:
  <<: *default
  database: sum_production
  username: blog
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
